## Do not edit this file in_place 
## Copy to $HOME and modify values there 

export highly_available_api_subscription_id=""
export highly_available_api_tenant_id=""
export highly_available_api_client_id=""
export highly_available_api_client_secret=""
export highly_available_api_resource_group_name="" ## www.example.com

