kind: Service
apiVersion: v1
metadata:
  name: demo-service
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer 
  selector:
    component: api-deployment
  ports:
    - name: api-deployment
      port: 8080
      targetPort: 5000
