kind: Deployment
apiVersion: apps/v1
metadata:
  name: api-deployment
spec:
  replicas: {{ .Values.replicas }} 
  selector:
    matchLabels:
      component: api-deployment
  template:
    metadata:
      labels:
        component: api-deployment
    spec:
      containers:
        - name: api
          image: {{ .Values.image }}
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /healthy
              port: 5000
        - name: oauth2-proxy 
          image: quay.io/oauth2-proxy/oauth2-proxy:v6.1.1 
          ports:
            - containerPort: 4180
          command: 
            - "oauth2-proxy"
            - "--upstream=http://localhost:5000/"
            - "--provider=azure"
            - "--client-id={{ .Values.client_id }}"
            - "--client-secret={{ .Values.client_secret }}"
            - "--cookie-secret={{ .Values.cookie_token }}"
            - "--email-domain=*"
            #- "--tls-cert-file=/path/to/cert.pem" TODO add tls 
            #- "--tls-key-file=/path/to/cert.key"
      imagePullSecrets:
        - name: acr-creds
