apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: demo-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: {{ .Values.web_domain }}
      http:
        paths:
          - path: /oauth2/callback
            backend:
              serviceName: demo-service
              servicePort: 8080 
          - path: /
            backend:
              serviceName: demo-service 
              servicePort: 8080
  tls:
    - hosts:
        - {{ .Values.web_domain }} 
      secretName: tls-secret 
