kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: api-ingress
spec:
  rules:
    - host: {{ .Values.host }} 
      http:
        paths:
          - path: /oauth2
            backend:
              serviceName: oauth2-service
              servicePort: 8080
          - path: /
            backend:
              serviceName: api-service
              servicePort: 8080
  tls:
    - hosts:
      - {{ .Values.host }} 
      secretName: tls-secret 
