kind: Service
apiVersion: v1
metadata:
  name: oauth2-service
spec:
  selector:
    app: oauth2-deployment
  ports:
    - port: 8080
      targetPort: 5000
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: oauth2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-deployment
  template:
    metadata:
      labels:
        app: oauth2-deployment
    spec:
      containers:
        - name: oauth2
          image: {{ .Values.oauth2_image }}
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /healthy
              port: 5000
          imagePullPolicy: Always
          command:
            - "python3"
            - "-u"
            - "app.py"
            - "--client-id={{ .Values.client_id }}"
            - "--client-secret={{ .Values.client_secret }}"
            - "--authority=https://login.microsoftonline.com/{{ .Values.tenant_id }}"
            - "--host=https://{{ .Values.host }}"
            - "--cookie-token={{ .Values.cookie_token }}"
      imagePullSecrets:
        - name: acr-creds
