kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: oauth2-proxy-ingress
spec:
  rules:
    - host: {{ .Values.web_domain }} 
      http:
        paths:
          - path: /oauth2
            backend:
              serviceName: oauth2-proxy-service
              servicePort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: oauth2-proxy-service
spec:
  selector:
    app: oauth2-proxy-deployment
  ports:
    - port: 8080
      targetPort: 4180
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: oauth2-proxy-deployment
spec:
  replicas: {{ .Values.replicas }} 
  selector:
    matchLabels:
      app: oauth2-proxy-deployment
  template:
    metadata:
      labels:
        app: oauth2-proxy-deployment
    spec:
      containers:
        - name: oauth2-proxy 
          image: quay.io/oauth2-proxy/oauth2-proxy:v6.1.1 
          ports:
            - containerPort: 4180
          command: 
            - "oauth2-proxy"
            - "--http-address=0.0.0.0:4180"
            - "--upstream=http://api-service:8080/"
            - "--provider=azure"
            - "--client-id={{ .Values.client_id }}"
            - "--client-secret={{ .Values.client_secret }}"
            - "--cookie-secret={{ .Values.cookie_token }}"
            - "--email-domain=*"
            - "--redirect-url=https://{{ .Values.web_domain }}/oauth2/callback"
      imagePullSecrets:
        - name: acr-creds
